/**
 * Assembles the site Vercel serves from this fork's Mermaid build.
 *
 * Run after `pnpm build:mermaid` at the repo root. It writes public/:
 *
 *   v/<version>/mermaid.esm.min.mjs + chunks/   ES module build, immutable
 *   v/<version>/mermaid.min.js                  classic <script> build
 *   v/<version>/diagram.js                      <infd-diagram>, imports the build beside it
 *   latest/...                                  the same files, cached for five minutes
 *   versions.json, index.html                   what is served, and how to use it
 *
 * and api/_mermaid.mjs, which points the parse API at the same bundle, so the
 * API and the pages always agree on one version.
 */
import { cp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const site = join(here, "..");
const dist = join(site, "..", "packages", "mermaid", "dist");
const out = join(site, "public");

if (!existsSync(join(dist, "mermaid.esm.min.mjs"))) {
  console.error(`No Mermaid build at ${dist}. Run \`pnpm build:mermaid\` at the repo root first.`);
  process.exit(1);
}

const { version } = JSON.parse(await readFile(join(site, "..", "packages", "mermaid", "package.json"), "utf8"));
const commit = process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 7) ?? "local";

await rm(out, { recursive: true, force: true });

async function release(dir) {
  const target = join(out, dir);
  await mkdir(join(target, "chunks", "mermaid.esm.min"), { recursive: true });
  await cp(join(dist, "mermaid.esm.min.mjs"), join(target, "mermaid.esm.min.mjs"));
  await cp(join(dist, "mermaid.min.js"), join(target, "mermaid.min.js"));
  // Source maps stay out: they are four times the size of the code.
  for (const f of await readdir(join(dist, "chunks", "mermaid.esm.min"))) {
    if (f.endsWith(".mjs")) await cp(join(dist, "chunks", "mermaid.esm.min", f), join(target, "chunks", "mermaid.esm.min", f));
  }
  await cp(join(site, "src", "diagram.js"), join(target, "diagram.js"));
}

await release(join("v", version));
await release("latest");

await writeFile(join(out, "versions.json"), JSON.stringify({ current: version, commit, versions: [version] }, null, 2));

const page = (await readFile(join(site, "src", "index.html"), "utf8")).replaceAll("{{VERSION}}", version).replaceAll("{{COMMIT}}", commit);
await writeFile(join(out, "index.html"), page);

await writeFile(
  join(site, "api", "_mermaid.mjs"),
  `// Generated by scripts/assemble.mjs. Do not edit.\nexport { default } from "../public/v/${version}/mermaid.esm.min.mjs";\nexport const version = ${JSON.stringify(version)};\n`,
);

console.log(`Assembled Mermaid ${version} (${commit}) into ${out}`);
